name: Build and deploy latex sources to GitHub Pages
on: push
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Russian
    - name: Build two-page russian
      uses: xu-cheng/latex-action@v2
      with:
        root_file: mmayer.tex
        working_directory: two-page_cv_ru
        args: -jobname=CV_ru
        compiler: latexmk
    - name: Upload two-page russian
      uses: actions/upload-artifact@v2
      with:
        name: two-page_cv_ru
        path: CV_ru.pdf
    # English
    - name: Build two-page english
      uses: xu-cheng/latex-action@v2
      with:
        root_file: mmayer.tex
        working_directory: two-page_cv
        args: -jobname=CV_en
        compiler: latexmk
    - name: Upload two-page english
      uses: actions/upload-artifact@v2
      with:
        name: two-page_cv_ru
        path: CV_en.pdf
