name: Build and deploy latex sources to GitHub Pages
on: push
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:202009150206298488ac
    strategy:
      matrix:
        lang: ["ru", "en", "de"]
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Build CS CV ${{ matrix.lang }}
      env:
        DIRECTORY: cs/${{ matrix.lang }}
        FILE: main.tex
      run: |
        cd $DIRECTORY
        latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf -outdir=$PWD $FILE
    - name: Upload CS CV ${{ matrix.lang }}
      uses: actions/upload-artifact@v2
      with:
        name: cs_cv_${{ matrix.lang }}
        path: cs/${{ matrix.lang }}/main.pdf
  create_release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [build]
    steps:
      - name: Variables
        id: vars
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d')"
          echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
        with:
          tag_name: cv-${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha8 }}
          release_name: CV (version ${{ steps.vars.outputs.date }})
          draft: false
          prerelease: false
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [create_release]
    strategy:
      matrix:
        lang: ["ru", "en", "de"]
    steps:
      - name: Download CS CV ${{ matrix.lang }}
        uses: actions/download-artifact@v2
        with:
          name: cs_cv_${{ matrix.lang }}
      - name: Upload CS CV ${{ matrix.lang }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./main.pdf
          asset_name: CS_CV_${{ matrix.lang }}.pdf
          asset_content_type: application/pdf
